Update exKbd.py
Driver was being initialized on the end. It would produce:
  File "main.py", line 66, in <module>
  File "m5inputs/base.py", line 178, in group
AttributeError: 'Keypad' object has no attribute '_driver'
If changed to before group creation it no longer gives an error.